name: Deploy to GitHub Pages

on:
  push:
    branches: [$default-branch]


  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: "6.x.x"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1
      - name: Install dependencies
        working-directory: watin/
        run: dotnet restore
      - name: Build
        working-directory: watin/
        run: dotnet build --configuration Release --no-restore
      - name: Publish with dotnet
        working-directory: watin/
        run: dotnet publish
      - name: Upload csproj
        uses: actions/upload-pages-artifact@v1
        with:
          path: watin/watin.csproj
      - name: Upload dll
        uses: actions/upload-pages-artifact@v1
        with:
          path: watin/bin/Debug/net6.0/watin.dll
      - name: Upload publish
        uses: actions/upload-pages-artifact@v1
        with:
          path: watin/bin/Debug/net6.0/publish
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Prepare deployment
        working-directory: watin/
        run: dotnet publish
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
